project:
  type: book

book:
  title: "MA42002"
  author: "Philip Murray"
  date: "12/22/2023"
  repo-url: https://github.com/dundeemath/MA42002/

  downloads: pdf

  chapters:
    - index.qmd
    - conservationequations.qmd
    - part: "Single species"
      chapters:
        - linearreactiondiffusion.qmd
        - nonlinearreactiondiffusion.qmd
      
    - part: "Multi species"
      chapters:
         - LotkaVolteraPDE.qmd
         - BacterialChemotaxis.qmd
         - DiffusionDrivenInstability.qmd
      #  - SIR_PDE.qmd
    - part: "Appendices"
      chapters:
        - NumericalMethods.qmd
        - linearstablityanalysis.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

