# Introduction {.unnumbered}


Welcome to MA42002 Mathematical Biology II.

My name is Philip Murray and I am the module lead.

## How to contact me?

* email: pmurray@dundee.ac.uk
* office: G11, Fulton Building


## Lecture notes
You can find lecture notes for the module on this page. If you would like a pdf this can be easily generated by clicking on the pdf link on the top left of the webpages. I will occasionally edit/update the notes as we proceed through lectures. If you spot any errors/typos/inconsistencies/omissions etc. please report an issue using the [report an issue](https://github.com/dundeemath/MA42002/issues/new) link on the right-hand side of the webpages.

## Reading 
Mathematical Biology II, @murray2003mathematical


## Python codes

I have provided Python codes for most of the figures in the html version of the notes (you can unfold code section by clicking `Code'). Note that the Python code does not appear in the pdf.

 Many of you have taken the Introduction to Programming module at Level 2 and have therefore some experience using Python. I strongly encourage you to use the provided codes as a tool to play around with numerical solutions of the various models that we will be working on. The codes should run as standalone Python codes.

## Plan

| Week | Up to Section | Tutorial sheet| Class Test |
|-------|:---|-----| ----|
| 1     | 1.3.3  |   1 |----|
| 2     | 2.1 |   1 |----|
| 3     | 3  |   2 |----|
| 4     | 3  |   2 |----|
| 5     | 4  |   3 | Yes|
| 6     | 4  |   4 |----|
| 7     | 5  |   4 |----|
| 8     | 5  |   5 |----|
| 9     | 6  |   5 |----|
| 10    | 6  |   6 | Yes|
| 11    | 7  |   6 |----|
: Projected delivery


## References