# Summary

Embryology or developmental biology is that part of biology which is concerned with the formation, growth and development of the embryo from fertilization until birth. From the very moment of conception the embryo undergoes a process of dynamic change, brought about largely by cells responding to various chemical signalling cues e.g. migration, differentiation, proliferation. Figure ref{embryogenesis} shows some of the major changes in embryonic development which occur up to a few weeks after fertilization. Many of the processes occurring at this early stage are vital for the successful subsequent development of the embryo and also lay down basic structures (e.g. [somites](https://en.wikipedia.org/wiki/Somite)) that form the foundation of major body structures later on (e.g. the vertebrae of the spine)  cf. Professor Lewis Wolpert: '*It is not birth, marriage, or death, but gastrulation which is truly the most important time in your life.*'



There are two main theories which describe how pattern arises during embryogenesis - one is the  *Turing pre-pattern theory*, the other is the *mechano-chemical* theory. In the Turing pre-pattern theory, chemicals, or [morphogens](https://en.wikipedia.org/wiki/Morphogen), react together and, if certain conditions concerning their reaction kinetics and diffusion rates are satisfied (to be derived in the next section), then a *pre-pattern* of varying chemical concentrations is set up in the spatial domain. This means that throughout the spatial domain, the concentration levels of the chemicals will vary i.e. there will be a *heterogeneous* distribution of chemical concentrations which is known as a pre-pattern. Any cells in the domain which subsequently encounter these varying levels of morphogens will then respond by, for example, proliferating differentially throughout the domain. In this way, the domain will then contain a {spatially heterogeneous} distribution of cell densities (i.e. a cellular pattern) which have responded to the morphogen pre-pattern. This pre-pattern theory was first proposed by Alan Turing (of Enigma Code fame) in his seminal 1952 paper, *The chemical basis of morphogenesis* @turing1990chemical. This was developed in more detailed manner by Alfred Gierer and Hans Meinhardt in another ground-breaking paper in 1972, *A theory of biological pattern formation* @gierer1972theory, where they introduced the concept of activating chemicals and inhibiting chemicals. J.D. Murray then applied the theory as an explanation for the generation of patterns observed on animal coats @murray1981pre. 

In the mechano-chemical theory, cells interact with their surroundings and by exerting forces perturb their local environment. The combination of cell migration/proliferation and cell-generated forces is sufficient in certain circumstances to create a spatially heterogeneous distribution of cell densities i.e. the pattern is generated *simultaneously* with the cell migration/proliferation.  This alternative pattern formation theory was proposed by Murray and Oster @murray1984generation and is particularly appropriate for patterns generated in early embryogenesis by *mesenchymal cells* such as fibroblasts. 

## Reaction-diffusion (Turing) Pre-pattern Mechanisms

We now consider our general (dimensional) reaction-diffusion model for two chemicals or morphogens with concentrations $A({\mathbf{x}}, t)$ and $B({\mathbf{x}}, t)$ which react together and diffuse in some spatial domain:

$$
\begin{aligned}
\frac{\partial A}{\partial  t} & =  F(A,B)  + D_A \nabla^2 A, \\
\frac{\partial B}{\partial  t} & =  G(A,B)  + D_B \nabla^2 B,
\end{aligned}
$$

where $F(A,B)$ and $G(A,B)$ describe the reaction kinetics between the two morphogens and $D_A, D_B > 0$ are the diffusion coefficients. Turing's theory (Turing, 1952) *The chemical basis of morphogenesis* proposed that it was the diffusion of the substances $A,B$ which led to the evolution of a spatially heterogeneous solution to arise i.e. a spatial pattern. This has given rise to the phrase *diffusion-driven instability*. This was a rather revolutionary and counter-intuitive proposal, since, as we have seen, diffusion normally has the opposite tendency i.e. to smooth or average out spatial heterogeneities, and to give rise to spatially homogeneous solutions.  

Various forms can be considered for the kinetic functions $F$ and $G$. However, we will focus mainly on three specific classes as follows:


### Schnackenberg kinetics

$$
F(A,B) = k_1 - k_2 A + k_3 A^2 B, \;\;\;\; G(A,B) = k_4 - k_3 A^2 B
$$

$k_1$, $k_2$, $k_3$, $k_4$ $>0$. The term $k_3 A^2 B$ is *autocatalytic*, since the species $A$ upregulates its own production. 

###  Gierer and Meinhardt kinetics

Gierer and Meinhardt developed a model that describes activator-inhibitor kinetics. The  total reaction rates are
$$
F(A,B) = k_1 - k_2 A + \frac{k_3 A^2}{B}, \quad G(A,B) = k_4 A^2 - k_5 B
$$

where
$k_1$, $k_2$, $k_3$, $k_4$, $k_5$ > 0. The term $k_3 A^2 / B$ is **autocatalytic**. 

### Thomas kinetics

Thomas developed a model of substrate inhibition in which
$$
\begin{aligned}
F(A,B) &= k_1 - k_2 A - H(A,B), \\
G(A,B) &= k_4 A^2 - k_4 B -H(A,B), \\ 
H(A,B) &= \frac{k_5 AB}{k_6 + k_7 + k_8 A^2}.
\end{aligned}
$$

with $k_i > 0$. In the original paper of Thomas (1975), $A$ represents the concentration of oxygen (substrate) and $B$ the concentration of uricase (enzyme). Substrate inhibition is evident in the term $k_8 A^2$. 

## Non-dimensionalization

Before proceeding further, it is prudent to non-dimensionalize each of the above systems. 

### Schnakenberg

We illustrate this process for the Schnakenberg kinetics. Using the scaling

$$
u = A \left( \frac{k_3}{k_2} \right)^{1/2}, \quad v = B \left( \frac{k_3}{k_2} \right)^{1/2}, \quad t^* = \frac{D_A t}{L^2},\quad x^* = \frac{x}{L},
$$

where $L$ is a typical length scale, the dimensionless reaction-diffusion system with Schnakenberg kinetics becomes (upon dropping the $*$ for notational convenience):

$$
\begin{aligned}
\frac{\partial u}{\partial  t} & = \gamma ( a - u + u^2 v ) + \nabla^2 u = \gamma f(u,v)  + \nabla^2 u, \\
\frac{\partial v}{\partial  t} & = \gamma ( b - u^2 v ) + d \nabla^2 v = \gamma g(u,w)  + d \nabla^2 v, 
\end{aligned}
$$ {#eq-schnackenbergeqns}

where 
$$
d = \frac{D_B}{D_A}, \quad a = \frac{k_1}{k_2} \left( \frac{k_3}{k_2} \right)^{1/2}, \quad b = \frac{k_4}{k_2} \left( \frac{k_3}{k_2} \right)^{1/2}, \quad \gamma = \frac{L^2 k_2}{D_A}.
$$

### Gierer and Meinhardt

The Gierer-Meinhardt kinetics can be non-dimensionalized as follows:

$$
\begin{aligned}
f(u, v) & =  a - b u + \frac{u^2}{v}, 
g(u,v) &= u^2 - v, \\
\end{aligned}
$$
where $a$ and $b$ are positive parameters (Exercise/Tutorial).

### Thomas

The Thomas kinetics can be non-dimensionalized as follows:
 
$$
\begin{aligned}
f(u,v) & =  a - u - h(u,v), \\
g(u,v) &= \alpha (b - v) - h(u,v), \\
h(u,v) & =  \frac{\rho u v}{1 + u + K u^2},
\end{aligned}
$$
where $a$ , $b$, $\alpha$, $\rho$ , $K$ are positive parameters (see Exercise/Tutorial).


### General

Any reaction-diffusion system can be non-dimensionalized and scaled following the above procedure to take the general form:
$$
\begin{aligned}
\frac{\partial u}{\partial  t} & = \gamma f(u,v)  + \nabla^2 u, \\
\frac{\partial v}{\partial  t} & = \gamma g(u,w)  + d \nabla^2 v, 
\end{aligned}
$$

where the parameter $d$ is the ratio of the diffusion coefficients and the parameter $\gamma$ can be interpreted in any one of the following ways:

* $\gamma^{1/2}$ is proportional to the  *linear size* of the spatial domain in one-dimension. In two-dimensions, $\gamma$ is proportional to the area. 
* $\gamma$ represents the relative strength of the reaction terms -- an increase in $\gamma$ may represent an increase in the activity of some rate-limiting step in the reaction sequence. 
* An increase in $\gamma$ is equivalent to a decrease in the diffusion coefficient, $d$. 

Note that in the case where the parameter $d > 1$, this means that the original diffusion coefficients are not equal. Specifically, in the case of the Gierer-Meinhardt activator-inhibitor system, $d >1$ implies that the inhibitor *diffuses more quickly* than the activator [$d > 1 \Rightarrow D_B > D_A$ ]. The spatial implications of this are shown in @fig_ai -- the inhibitor diffuses a greater distance than the activator, giving rise to what is known as *local activation, long-range inhibition*. 







In @fig-schnack_ddi_pde we plot numerical solutions of @eq-schnackenbergeqns with no flux boundary conditions. 

In this numerical solution the initial condition are the spatially homogeneous steady state perturbed by uniformly sampled noise. As time evolves, a spatial pattern emerges. The main idea from a biological perspeftive is that an unpatterned region of an embryo could undergo chemical reactions, with the result being a patterned chemcial field. 

Some question that might arise:

* How does pattern formation depend on model parameters?
* How does pattern formation depend on domain size?
* How does the pattern wavelength depend on model parameters?
* How does the pattern depend on the initial conditions?
* How can we numerically solve the reaction diffusion PDEs?


